### ISSUE TITLE
Can we rename  this repo to htmd-pdb2pqr?

### ISSUE THREAD

**Issue by tonigi** [Acellera/conda-pdb2pqr#1]
So it's the same as the package it builds

**Comment by giadefa** [comment]
done, but in travis is still called conda- 
@mj-harvey can you fix it?

**Comment by mj-harvey** [comment]
Why?

**Comment by tonigi** [comment]
The idea was to be consistent between the repo name and conda package name. But now im seeing that it was like all the many other conda-\* repos. Feel free to undo.
